apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  namespace: session20
  labels:
    app: gitops-demo
spec:
  type: NodePort
  selector:
    app: gitops-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30200
